django/publicmapping/publicmapping/views.py
Remove unique constraint of email on signup. 
* Sign up multiple times with different usernames but same emails
=> Remove unique constraint for user email on signup

django/publicmapping/config/config.xml
The info panel was configured with the same position as the summary panel. Position is used to determine display order. This caused a non-deterministic bug where sometimes it was possible for the order of the two panels to be reversed.
- [x ] PR has a name that won't get you publicly shamed for vagueness
This is a trivial fix that is hard to test due to it's non-deterministic nature. I've already applied the fix to staging and it works, so I'm just going to merge this.
=> Fix info panel position

django/publicmapping/config/config.xml, django/publicmapping/static/js/mapping.js
This enables the base map switcher and adds a couple new types of base maps.
Probably best to look at the commits separately, since the `Formatting` commit was just a trailing whitespace getting automatically trimmed.
* I believe you can get this working by just SSHing into the VM and running `scripts/update`. This should copy the basemap settings over to the appropriate place.
* Then just load the map and verify that each of the basemap options works
=> Enable base map switcher

django/publicmapping/publicmapping/templates/account.html, django/publicmapping/static/js/register.js
This makes the email input required on account sign up.
* Build and serve 
* On the home page, click "Sign Up". Make sure the email field has a * on the label, the note above is says that the email is required, and that the form will not submit without entering an email.
=> Make email required on signup

Vagrantfile
Peter and I were running into issues with .po files. This is because for us rsync wasn't adding the .po files in the `locale` directory to the VM. Rsync excluding only .mo files fixes this. It also enables the modified .po files to be written back to the host with rsync back. 
* `vagrant destroy`
* `vagrant up`
* `vagrant ssh`
* `./scripts/update`
* `./scripts/configure_pa_data`
* `./scripts/server`
* Play with the app and see it it works
=> Fix translation error

django/publicmapping/config/config.xml, django/publicmapping/context_processors.py, django/publicmapping/redistricting/templates/editplan.html, django/publicmapping/redistricting/views.py
C70 wants to collect additional parameters for contest submissions. This adds those parameters to the contest submission form, but doesn't go any further than that (see notes).
- The requested functionality, and the description for this task, both assume that the parameters entered in the contest submission form are being stored in the database. However, that turns out not to be the case; instead, the form contents are immediately emailed to a configurable email address, along with a CSV export of the relevant plan, and then forgotten:
- https://github.com/azavea/district-builder-dtl-pa/blob/feature/capture-contest-details-%23156479506/django/publicmapping/redistricting/views.py#L2071
- https://github.com/azavea/district-builder-dtl-pa/blob/feature/capture-contest-details-%23156479506/djan …
=> Capture DTL contest details

Vagrantfile, deployment/ansible/district-builder.yml, deployment/ansible/group_vars/all, deployment/ansible/roles/district-builder.pre-commit/tasks/main.yml, deployment/ansible/roles/district-builder.python/tasks/main.yml, locustfile.py
POC load testing script using Locust.
**Configure Test through web UI**
**Test in progress**
This story was to choose a load testing tool for the DistrictBuilder PA instance. After some preliminary research, a few categories of tools emerged:
1. Full-featured GUI-based load testing applications written in Java (eg. JMeter, The Grinder, Gatling)
1. More obscure tools (eg. Tsung, written in Erlang and requiring you to write Bash & Perl scripts)
1. Locust (simple, very developer-friendly, written in Python)
Immediately Locust emerged as the front-runner. Using it amounts to running `pip install locustio`, writing a simple Python script, choosing the number of users and hatch rate, and running a test in the browser. Since do not have well-defined requirements for exactly what or how to test, …
=> Use LocustIO for load testing #156858139

locustfile.py
Updates the locustfile to mimic the activity recorded during a 5-minute redistricting session.
- In the interest of time, I ignored any URL patterns that had fewer than 10 requests within the 5-minute testing span. I'm attaching the raw data so that these can be added later if necessary.
[requests.csv.txt](https://github.com/azavea/district-builder-dtl-pa/files/1981366/requests.csv.txt)
* Bring up your VM and then `./scripts/server`
* In another terminal, `vagrant ssh` and then `locust`
* Browse to `http://localhost:8089` and start swarming.
* Double-check that cookies are working in the way this expects and that the requests are actually testing the real operations and not short-circuiting because of auth issues; I *think* I got everything right and the API seems to be returning 200s, …
=> Add locustfile with real-world request proportions

django/publicmapping/publicmapping/templates/facebook_sdk.html, django/publicmapping/publicmapping/templates/index.html, django/publicmapping/redistricting/templates/viewplan.html
Swaps out the Facebook Like buttons on the homepage and plan Sharing page for FB Share buttons instead.
- Doing this uncovered that the domain name isn't getting properly set in `settings.py`. We currently always set `ALLOWED_HOSTS` to `['web']`, which is what results from running via docker-compose, but this means that whenever Django generates a hostname, it ends up as `http://web/whatever/` which is incorrect. We're going to need to make sure that we can tell Django what domain it is running on; I've added [#157125912](https://www.pivotaltracker.com/story/show/157125912) for this.
- The dialog that pops up when you click this button always closes immediately, whether or not you are logged into Facebook. I suspect that this is because FB is detecting the invalid domain name problem and …
=> Switch to FB share button from Like button

django/publicmapping/config/config.xml, scripts/configure_pa_data, scripts/load_configured_data
This PR switches the geolevel(s) from municipalities to counties and tracts, and also includes some preliminary voter info configuration.
* ssh into the VM and run: `scripts/configure_pa_data` (note: this will clear your database)
* Run `scripts/server`
* Browse to the site, create a user, and create a plan from a template
* Ensure counties are visible at the min zoom level, but as you zoom in, it switches over to tracts
* Add a new statistics set that includes some of the new voting-related fields
* Make a valid plan! It's actually really easy now, if you chose the 'new' template
* Submit it to the leaderboard, and ensure that the Competitiveness score shows up.
=> Switch to census-based shapefiles

django/publicmapping/config/config.xml
Translating to Spanish is not covered in this round of funding. Removing the option, since the Spanish translations will only be partially working until we have the time to perform the translations.
* `vagrant ssh`
* `scripts/update` (important -- this reads the `config.xml` file and creates a new `config_settings.py`
* `scripts/server`
* Browse to the app and verify that there is no language dropdown for Spanish.
I was hoping having one language option would hide the language dropdown, but it doesn't. We'll need to add some logic if that's the desired behavior.
=> Remove Spanish language option

docker-compose.yml
Previously, only one subfolder of GEOSERVER_DATA_DIR (`/data/sld`) was persisted using a Docker volume mount. As a result, anytime GeoServer was removed and re-created, the remaining configuration (reset password, stored layers) were lost. This commit makes the entire GEOSERVER_DATA_DIR persistent by using a Docker volume.
https://pa.districtbuilder.azavea.com
This change has been applied to Staging. On the PA App Server, I  did the following:
```bash
$ cd /opt/district-builder
$ docker-compose down -v
$ sudo restart district-builder
$ docker exec -it districtbuilder-geoserver ./bin/change_admin_password.sh
$ docker exec -it districtbuilder-app ./manage.py setup config/config.xml -G
$ sudo restart district-builder
```
* SSH into the PA App server
* run `sudo restart district-builder`
* …
=> Make geoserver data dir persistent

django/publicmapping/config/config.xml, django/publicmapping/redistricting/calculators.py
Adds competitiveness to the plan scores section in the sidebar.
I don't love the code for adding the target formatting to the calculator, but this is the same way it's done in several other calculators, so I wanted to keep it identical in case we want to refactor them all in the future.
* ssh into the VM and run: scripts/configure_pa_data (note: this will clear your database)
* Run scripts/server
* Browse to the site, create a user, and create a plan from a template
* Verify that a Competitiveness score shows up on the sidebar, and is formatted such as `x (of 18)`
* For extra credit, make a valid plan, submit to the leaderboard, and ensure the competitiveness score just shows the raw number, rather than the `x (of 18)` formatting. 
Closes #157605960
=> Add competitiveness score to sidebar

django/publicmapping/config/config.xml, django/publicmapping/static/js/mapping.js
This PR adds a selectable Mapbox basemap whose purpose is to show municipalities. The list of configured basemaps in order from left to right is now: ESRI topo, ESRI road, and Mapbox municipalities (OSM and ESRI dark have been removed per client request).
I checked with Tyler, and it is not necessary to account for the configuration of multiple Mapbox basemaps, or any fancy URL configuration. If we want to change the URL or token, we will just modify the JavaScript file.
* vagrant ssh
* scripts/update
* scripts/server
* Browse to the map page and verify that there is a `Municipalities` selection available. Choose it and verify that the Mapbox tiles are displaying.
=> Add Mapbox municipalities basemap

django/publicmapping/requirements.txt
Secondary dependency (`kombu`) broke out from under us. This is the same fix as:
https://github.com/WikiWatershed/model-my-watershed/commit/008d02befce5533a6ee56302b84db2507b53ec13
- ~[ ] Files changed in the PR have been `yapf`-ed for style violations~
* On `develop`, to reproduce the broken state you would find yourself in with a fresh repo, make this change:
```diff
diff --git a/django/publicmapping/Dockerfile b/django/publicmapping/Dockerfile
index 67b6538..fc04081 100644
--- a/django/publicmapping/Dockerfile
+++ b/django/publicmapping/Dockerfile
@@ -17,7 +17,7 @@ RUN apt-get update && apt-get install -y \
git gcc wget unzip
COPY requirements.txt /usr/src/app/
-RUN pip install --no-cache-dir -r requirements.txt
+RUN pip install --no-cache-dir --ignore-installed -r requirements.txt …
```
=> Pin to kombu==4.1.0 to avoid breaking Celery

Vagrantfile
Exclude `xmlconfig.po` from Vagrant rsync.
`xmlconfig.po` is derived from `config.xml`. As such, it should not be put into the VM where it overrides the `xmlconfig.po` file generated by the `django` container.
There was a bug that manifested itself as follows: whenever a file was changed with `vagrant rsync-auto` running, `xmlconfig.po` within the VM would be overwritten. If you would re-configure by running `./manage.py setup config/config.xml`, the file would then be generated correctly, but any other change to a file with rysnc-auto running would overwrite it again.
This change makes it so that other `.po` files that are committed to source control with proper translations (such as `django.po`) will still make their way into the VM while `xmlconfig.po` will not.
A change to fix …
=> Exclude xmlconfig.po from Vagrant rsync

django/publicmapping/redistricting/reportcalculators.py
Fix Polsby-Popper reports by adding `PolsbyPopper` as a calculator for compactness reports.
**Now looks like this**
**Invalid config should show this**
* On this branch, run app (restart app if running)
* Create new plan
* Click "Evaluate" tab
* Select "Polsby-Popper" and then click "Create and Preview New Report" button
* Observe report is correctly generated
Note that there is a lot of caching. You need to both restart the app and also create a new plan for this to work correctly.
=> Fix Polsby-Popper reports

django/publicmapping/redistricting/views.py
Order score displays alphabetically by title.
This seems like a reasonable default ordering, happens to achieve what we want ("Basic Information" showing up first), and is much quicker and easier than making changes to allow for configuring the display order.
Run app and make sure that "Basic Information" is the first option in the dropdown:
https://www.pivotaltracker.com/story/show/157411581
=> Order score displays alphabetically by title #157411581

django/publicmapping/redistricting/views.py, docker-compose.yml
This fix was already implemented for DistrictBuilder core. This PR just includes the cherry-picked commit from https://github.com/PublicMapping/DistrictBuilder/pull/535/files
Probably doesn't need to be fully tested because of ultra-turbo-pteradactyl mode. Just compare the changes to https://github.com/PublicMapping/DistrictBuilder/pull/535/files and make sure they make sense.
=> Fix district index file upload

django/publicmapping/redistricting/management/commands/submission_report.py, django/publicmapping/redistricting/templates/submission_summary.html
Embeds Leaflet directly into the plan submission single-page report, so that it doesn't have to be hosted anywhere for the page to work. The page is now fully self-contained except for map tiles.
* Follow the instructions from https://github.com/azavea/district-builder-dtl-pa/pull/36 to get a plan submission HTML report.
* Verify that the new HTML report embeds Leaflet.js and leaflet.css in the document rather than linking to them (and that it renders correctly, obviously).
=> Embed Leaflet into plan submission report

scripts/update
Reconfigure on update.
This will cause translations in `config.xml` to be regenerated whenever we deploy.
First let's get to the state where staging is at, then we'll fix it.
* Turn off `vagrant rsync-auto` if running
* Check out the commit prior to the one where translations were fixed (bebecba)
* `vagrant reload` to make the changes to _not_ exclude the `xmlconfig.po` files take effect
* `./script/server`
* Visit http://localhost:8080/districtmapping/plan/2/view/ and notice that the translations in the metrics pane to the right are broken
* Check out this branch
* `vagrant reload` again (`xmlconfig.po` is now excluded and won't overwrite what's in the VM/container)
* Run `./scripts/server` and make sure the translations are still broken
Now we are in the state staging is at. Let's fix …
=> Fix translations by reconfiguring on update #158341090

django/publicmapping/redistricting/management/commands/submission_report.py, django/publicmapping/redistricting/templates/submission_summary.html
Adds district labels to the submission report page. Also filters out the unassigned catch-all district since it was generating a confusing label.
* Same as #36 but each district on the map should have a label now.
Closes #158324032
=> Add district labels to submission report map

django/publicmapping/redistricting/models.py, django/publicmapping/redistricting/templates/editplan.html, django/publicmapping/redistricting/templates/submission_summary.html
Calculates and displays a plan submission's region, according to the region breakdown given to us by C70. As part of this, changes the County item in the submission form from a text input to a dropdown.
I could have made this more robust by adding a `choices` parameter to the `county` field of `PlanSubmission`. In the interest of time, I opted to skip that, so the only validation is from the dropdown in the UI. If someone uses an HTTP client to submit plans directly to the API endpoint and inputs bogus county names, the worst that could happen is that the region will show up as "Unknown (county name)" in the report.
* Same as #36 but do it a few different times with counties from different parts of the state and verify that the region shows up as Western, Central, or Eastern …
=> Add region to Submission report

django/publicmapping/config/config.xml, django/publicmapping/redistricting/views.py, django/publicmapping/static/js/mapping.js, scripts/update
C70 requested changes to the display of the info popup.  They would like to display the 5 following demographic data points:
Total Population
Total White Population
Total Black Population
Total Hispanic/Latino Population
Total Asian Population
This PR makes changes to `views.py` and `config.xml` to reorder the demographic Subjects and increase the number of elements listed on the info popup to include the ones they want.
I made changes in what I believe to be the appropriate places to make this happen based on Kenny's message in #district-builder.  However I don't have a development environment to test these changes. I'm hoping this small change can save some developer time doing it, so I would like someone to test this out and see if the changes work. If it doesn't end up just working, …
=> Rework config for info popup display

django/publicmapping/config/config.xml
Removes the Community Maps Legislative Body, which in turn causes the dropdowns for selecting a legislative body to disappear.
* In order to deploy this it will be necessary to perform the testing steps on staging; I checked, and the setup script (or at least, the part of it that handles `LegislativeBody`s) can only create data, not delete it, so we'll need to manually remove the old Community Maps `LegislativeBody`.
* I don't _think_ this impacts translations in any way because in the worst case it removes translation strings so our old .po file should still have the right translations in it, but let me know if you think that's not correct.
* `./scripts/server`
* In another shell `docker-compose exec django bash`
* Then `./manage.py shell_plus`. Once you're in, grab the community maps …
=> Remove "Community Maps" legislative body

django/publicmapping/config/config.xml, django/publicmapping/redistricting/calculators.py
Show number of majority-minority districts in side bar.
An issue with the shapefile was identified and subsequently fixed while working on this feature. The `TOT18O_POP` field was not actually total VAP but total _non-hispanic_ VAP. A change was made to add `O18HISPAN` to the value in this field to get the true total VAP.
* `./scripts/configure_pa_data && ./scripts/server`
* Select "Demographics" from the dropdown in the side bar and make sure the percentages for "Asian VAP", "Black VAP", and "Hisp. VAP" make sense relative to the "Majority-Minority" count.
Closes #158613616
=> Show number of majority-minority districts in side bar #158613616

django/publicmapping/publicmapping/templates/index.html, django/publicmapping/publicmapping/templates/language_chooser.html, django/publicmapping/redistricting/templates/viewplan.html
Brief description of what this PR does, and why it is needed.
The support link is currently a placeholder (`https://drawthelinespa.org/`). To change it, we need to edit that link on `django/publicmapping/publicmapping/templates/index.html` and `django/publicmapping/redistricting/templates/viewplan.html`.
* Checkout branch, `./scripts/server`, check if the 4 items above look good.
=> Update links and buttons on header

django/publicmapping/locale/en/LC_MESSAGES/django.po, django/publicmapping/locale/en/LC_MESSAGES/djangojs.po, django/publicmapping/publicmapping/templates/index.html, django/publicmapping/redistricting/templates/shared_feed.xml
Change all occurrences of "map" to "plan".
Overall, DistrictBuilder is very good about using translations everywhere so this mostly involved updating the `.po` files.
`config.xml` is one place where we aren't doing translations. There is one occurrence of "plan" ("Plan Summary") but that text doesn't appear to actually show up in the UI at all.
I'm not sure if `shared_feed.xml` is being used anywhere but I translated it just in case.
Also worth noting that there won't be any reporting functionality used so we don't have to worry about translating anything related to reports.
* `./scripts/server`
* `docker-compose exec django bash`
* `./manage.py setup config/config.xml`
* Kill and run `./scripts/server` again
* Observe new translations
Closes #158609169
=> Change all occurrences of "plan" to "map"

deployment/terraform/variables.tf
When working on PublicMapping/DistrictBuilder/pull/552, I noticed that there were some unnecessary Terraform variables. This PR cleans them up (and I've removed them from the file on S3)
* Apply the following diff:
```diff
diff --git a/docker-compose.ci.yml b/docker-compose.ci.yml
index 60d3eca4..f36caf03 100644
--- a/docker-compose.ci.yml
+++ b/docker-compose.ci.yml
@@ -7,8 +7,7 @@ services:
working_dir: /usr/local/src
entrypoint: bash
environment:
-      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
-      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
+      - AWS_PROFILE=district-builder
- AWS_REGION=${AWS_REGION:-us-east-1}
- DB_DEBUG=1
- IMAGE_VERSION=${IMAGE_VERSION:-latest}
@@ -17,3 +16,4 @@ services:
volumes:
- …
```
=> Remove unnecessary variables from Terraform config

django/publicmapping/redistricting/calculators.py, django/publicmapping/redistricting/templates/viewplan.html
Remove district thematic map shading and teal/yellow colors from demographics panel.
* Start server and log in
* Go to Draw
* Check to see that map does not have teal/yellow district shading.
* Check to see that map legend does not have teal/yellow colors.
* Check to see that demographics sidebar does not have teal/yellow colors.
* Click "Set Map Layers" and check to see that "Choose District Thematic Map" panel isn't visible.
=> Remove district thematic map shading

django/publicmapping/static/js/mapping.js
Makes District labels more easily readable.
Before
After
* Load up any map and see that the labels now have white halos around them and are easily readable on all types of backgrounds.
Closes #158993075
=> Add white halo to map labels for readability

django/publicmapping/static/js/layerchooser.js
Make the default reference layer `county` instead of no reference layer by default.
* Start server and go to map
* See that the map loads with counties as the reference layer (green outlines)
* See that on clicking "See Map Layers" the chosen value is `county`
=> Make default reference layer county

django/publicmapping/redistricting/templates/viewplan.html
Change order of opacity slider and basemap picker and add labels
- ~[ ] Files changed in the PR have been `yapf`-ed for style violations~
CSS will be added later by a designer. For now some minimal CSS was added inline.
* If server is not running, `./scripts/server`
* If running, `docker-compose restart django`
Closes #158995111
=> Change order of opacity slider and basemap picker and add labels #158995111

django/publicmapping/config/config.xml, django/publicmapping/redistricting/views.py, django/publicmapping/static/js/mapping.js
Add registered voter subjects to tooltip, similarly to https://github.com/azavea/district-builder-dtl-pa/pull/39
* `./scripts/update && ./scripts/server`
Closes #158995145
=> Add registered voters to tooltip #158995145

docker-compose.override.yml, docker-compose.production.yml, docker-compose.yml, scripts/update
Gets rid of the `languages` container in favor of making translations on update.
On staging, the `django.mo` and `djangojs.mo` files were missing:
```
root@87657c9f6aac:/usr/src/app# ls -l locale/en/LC_MESSAGES/
total 224
-rw-rw-r-- 1 root root 75265 Jul 16 18:49 django.po
-rw-rw-r-- 1 root root 21608 Jul 16 18:49 djangojs.po
-rw-r--r-- 1 root root 38667 Jul 16 18:58 xmlconfig.mo
-rw-rw-r-- 1 root root 83376 Jul 16 18:58 xmlconfig.po
```
It's not entirely clear why this is so. Translations are supposed to be compiled whenever the containers are spun up. The way deployment is currently that doesn't seem to be happening.
This PR moves the making of translations into `scripts/update`. This seems like a good place for …
=> Fix translations on staging

django/publicmapping/static/js/mapping.js
Each district should be a different color. The outlines should be darker. 
* Open a not blank map and see the color. Interact with the map and see them change as you edit districts.
* Open a blank map and start creating districts. Watch them get colored.
=> Color each of the 18 districts differently

django/publicmapping/config/config.xml, django/publicmapping/redistricting/calculators.py, django/publicmapping/redistricting/management/commands/submission_report.py, django/publicmapping/redistricting/templates/submission_summary.html
Adds a line for county splits to the submission summary one-page report.
* I _think_ it should be safe to simply run `./manage.py setup config/config.xml`, but to be on the safe side, I suggest opening a Django shell and running `ScorePanel.objects.all().delete()` and `ScoreFunction.objects.all().delete()`, and then run the setup command afterward.
* Follow the instructions for testing #36 
* Confirm that there is a new line displayed, for the number of split counties.
* Use the "Splits Report" feature of the mapping UI to confirm that the reported number of splits matches up with what the "Splits Report" outputs. 
Closes #158292949
=> Add total county splits to submission summary page

django/publicmapping/static/js/districtfile.js
Add tooltips to explain download buttons on plan/map page.
* Log in and go to map page. Select a map. Hover over the download buttons on the bottom right and confirm that the tooltips show up. 
* Here's the text you should looking for `Downloads a zipped .csv file that maps census tracts to districts for this map.` for the `Request Index File` button and `Downloads a zipped ESRI shapefile (.shp) of this map that can be viewed in GIS software.` for the `Request Shapefile` button.
Closes #159331229
=> Add tooltips to explain download buttons on plan/map page

django/publicmapping/redistricting/views.py, django/publicmapping/static/js/mapping.js
The timestamp on the bottom of the Draw page was showing what appeared to be PT instead of ET. This fix makes sure it shows the local time of the server, which will be ET or EST as needed. This also makes a fix to update the timestamp when a new district is created. Currently, the timestamp is only updated when a geounit is reassigned to an existing district. 
* Create a new map (from a template, say) and find yourself in the Draw tab. 
* Look at the timestamp. It should be the created time in Eastern.
* Wait till the minute changes. 
* Assign a geounit to an existing district. Verify that the timestamp updates.
* Refresh and verify the time still persists. 
* Wait till the minute changes. 
* Assign a geounit to a brand new district (to do this you might have to assign all geounits of a …
=> Fix timestamp bugs

deployment/README.md, docker-compose.ci.yml, scripts/infra
Updates deployment instructions to reflect the change to a new AWS account/SSH keypair. Additionally, change `DOCKER_HOST` to `DB_DOCKER_HOST` in `docker-compose.ci.yml` to avoid accidentally overriding the deployment environment's `DOCKER_HOST` when running Production deployments.
Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.
* Verify that the changes made to the `README` are accurate.
=> Update deployment README

django/publicmapping/config/config.xml
Uses the alphabetical-prefix-ordering trick to set a specific ordering for map-level stats in the sidebar.
- The ordering for Splits was not specified, but this modifies most of the ScoreFunctions that are used in the one-page summary report, so the ordering will change there, too. In the summary report the splits will be the third item (i.e. between Contiguity and Competitiveness).
- This is targeted at #65 currently to avoid conflicts, but I'll rebase and retarget to `develop` once that's merged.
* Open a Django shell and delete all `ScoreFunction`s, `ScorePanel`s and `ScoreDisplay`s.
* Run `./scripts/update`
* View the map edit page and confirm that the ordering of the sidebar summary stats matches what is required in #159332077
Closes #159332077
=> Change ordering of plan-level summary stats to match C70 requirements

django/publicmapping/config/config.xml, django/publicmapping/locale/en/LC_MESSAGES/django.po, django/publicmapping/locale/en/LC_MESSAGES/xmlconfig.po
Update copy.
The copy was changed as part of a larger set of config changes in https://github.com/azavea/district-builder-dtl-pa/pull/65 but the text was wrapping and didn't look great so C70 changed it again.
Should look like this now:
`./scripts/update && ./scripts/server`
=> Change copy for side panel

django/publicmapping/redistricting/templates/editplan.html, django/publicmapping/redistricting/templates/viewplan.html
Change header text and add sentence to explain upload map.
* Log in and ensure that the buttons on the header are `Select > Map > Evaluate > Submit` instead of `Map > Draw > Evaluate > Submit`
* On the `Select` page, go to `Upload Map` and ensure that there are two sentence, the second with a link as specified on the story.
Closes [#159536735](https://www.pivotaltracker.com/story/show/159536735) and [#159309223](https://www.pivotaltracker.com/story/show/159309223)
=> Change header text and add sentence to explain upload map

.travis.yml, scripts/infra
Add some `.travis.yml` changes that came about as I was working on #76. These changes largely serve to increase build output and logging, and to make sure that the build itself won't run forever. 
- I put a hard limit on the number of times we'd check to see if the docker daemon is running
- Replaced the `curl` check with one based on `docker-compose`. 
- Use a fix suggested in https://github.com/travis-ci/travis-ci/issues/8973 to ensure that deployment logs are captured in console output.
- [x ] PR has a name that won't get you publicly shamed for vagueness
Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.
* `develop` and …
=> Changes from investigating AppServer deployment failures

django/publicmapping/redistricting/templates/viewplan.html, django/publicmapping/static/css/core.css
Moves the hidden Reference Layer status line from the basemap control, on the upper right of the map, down to the status bar, on the lower left of the map. Also unhides it.
* View a map, confirm that the Reference Layer displays "County Lines" upon initial map load.
* Change the reference layer to Census Tracts and None, and confirm that the reference layer display in the status bar behaves as you expect.
Closes #159991025
=> Move Reference Layer info to lower left status bar

django/publicmapping/redistricting/views.py
Submissions were showing up in the Leadboard because all plans where `is_valid` is `True` show up there. This sets that value to `False` for submitted plans (which are copied from valid plans).
* Create a valid Plan
* Validate and submit it
* Verify that the plan you are submitting itself shows up on the Leaderboard but that a plan with a name similar to `Submission by: username 0.5830290` does not (repeat these steps on `develop` or staging if you want to see this happen).
Closes #159431140
=> Don't display submissions on the Leaderboard

django/publicmapping/static/css/core.css
Assign to District is explicitly set to white and disappears against the new background. I missed this in my feedback to Jeff, so I'm making the change myself. 
Tested this in the browser by removing the `color:` line in CSS:
Just a trivial CSS change. Don't know if there's a best practice to remove the `color` element or explicitly set it to black, but feel free to let me know in the comments.
* Log in and load up a map
* Assign to District should be visible as black against white background
=> Remove Assign to District white color

django/publicmapping/static/js/statisticssets.js
Require map to be re-validated after a change
* Make a valid map (or use https://github.com/azavea/district-builder-dtl-pa/files/2328961/testnew.zip if you need it)
* Reassign a geounit to render the map invalid
* Go to "Submit" tab and observe that the map must be re-validated to submit and form elements are properly disabled/greyed out.
* Click validate and observe the error
* Go back to map and reassign the geounit to its original district (the "Undo" feature doesn't seem to actually do this, which you'll notice if you refresh the page and see that your undone change has been redone...)
* Validate again and you should then be able to submit  
Closes #160000139
=> Require map to be re-validated after a change #160000139

django/publicmapping/config/config.xml
Fixes https://www.pivotaltracker.com/story/show/160431658
Run `./scripts/configure_pa_data`, create a new user and log in, and then follow steps to reproduce in bug ticket.
=> Fix typo in Age 65+ field name

.travis.yml, deployment/terraform/templates/cloud-config.tpl
Sets up a cronjob that runs `docker system prune`  daily on the app server. This should help speed up builds on the app server, and keep Travis from timing out. 
- Update cloud-init script to write out `/etc/cron.d/docker-prune`, which prunes docker images daily
- Install `vim` on the app server, which has no text editor at all
- Stop the ECS service, and disable upstart service by commenting out the `start on` configuration parameter.
- Undo the work in #77 that turns up travis logging. It's no longer necessary, and is actually so verbose that deployments are not visible in the travis console logs.
Optional. Ancillary topics, caveats, alternative strategies that didn't …
=> Add cronjob to remove old images from App Server

django/publicmapping/publicmapping/templates/forgottenpassword.email, django/publicmapping/publicmapping/templates/index.html, django/publicmapping/publicmapping/urls.py, django/publicmapping/publicmapping/views.py, django/publicmapping/static/js/register.js
This PR changes the password reset workflow to ensure that a password is only reset when both username and email are provided. 
With the new workflow, the user needs to enter both username and email to get a hint. Then, the user can either close the popup or opt to receive a new password sent to them.
* Click "Forgot Password"
* Test to see that you need a correct pair of both username and email to get a hint.
* Test to see that on clicking "Reset Password" after getting the hint, the password is reset and an email is sent (or logged in the debugger).
Closes [#160316709](https://www.pivotaltracker.com/story/show/160316709)
=> Change password reset workflow

django/publicmapping/publicmapping/templates/index.html, django/publicmapping/redistricting/templates/editplan.html, django/publicmapping/static/js/emailplan.js
Add share buttons to successful submit popup and change share text. 
* Validate and submit a plan
* Verify that the successful submit popup has share buttons
* Confirm text changes to popup and to share buttons (Tweet and Email are good examples)
Closes [#159998819](https://www.pivotaltracker.com/story/show/159998819)
=> Add share buttons to successful submit popup

django/publicmapping/redistricting/calculators.py, django/publicmapping/redistricting/tests/test_score_render.py, django/publicmapping/redistricting/tests/test_scoring.py, django/publicmapping/static/js/mapping.js
Make population and percentages numbers more readable. 
- Reduce all percentage stats to 1 decimal place
- Add commas to all population numbers
- Drop the decimal from the populations in the map legend
* Check that all populations on the stats panel have commas. Check to see this is true with big numbers and small numbers.
* Check the map legend to see that the populations have commas but no decimals.
* Check that all percentages on the stats panel have only 1 decimal place. 
Closes [#160602296](https://www.pivotaltracker.com/story/show/160602296)
=> Make numbers in app more readable

django/publicmapping/redistricting/models.py
The query for obtaining contiguity overrides is slow, because it is being passed in a large piece of WKB. This commit first checks to see if any contiguity overrides are defined before issuing the query.
* To see how massive the query was beforehand:
* Don't checkout this branch yet
* Enable DEBUG mode in Django
* `vagrant ssh`
* `docker-compose exec django ./manage.py shell_plus --print-sql`
* `from redistricting.calculators import Contiguity; Contiguity().compute(plan=Plan.objects.all()[0])`
* Watch as the WKB flows down your terminal
* Do this again with this branch in place and notice a much more reasonable set of query output
* Load up the UI and ensure that scores are still calculating correctly -- particularly the contiguity score, which is the only thing this code change affects
=> Avoid large contiguity overrides query if none exist

docker-compose.production.yml
Override the gunicorn command arguments in `docker-compose.production.yml` to disable `--reload` and make `--log-level=INFO` in built container images.
Fixes #100 
My thinking in adding an override to `docker-compose.production.yml` was because of this preexisting mechanism:
https://github.com/azavea/district-builder-dtl-pa/blob/70ff4f1abca514289be4bb9a3b942c97beaaf3d1/scripts/update#L64-L68
First, setup your environment for DistrictBuilder DTL staging:
```bash
$ export AWS_PROFILE=district-builder-pa
$ export DB_SETTINGS_BUCKET=district-builder-dtl-staging-config-us-east-1
```
Download Docker client certificates from S3 and unzip:
```bash
$ aws s3 cp s3://${DB_SETTINGS_BUCKET}/docker_certs/client/client.zip ./client.zip
$ unzip ./client.zip -d client
```
Configure remote Docker host: …
=> Override gunicorn command in production

deployment/terraform/compute.tf, deployment/terraform/templates/cloud-config.tpl, deployment/terraform/variables.tf
This PR updates adds a CloudWatch logs configuration to ship `dmesg`, `/var/log/messages` (which includes application logs) and `/var/log/docker` from the App Server to a CloudWatch logs group. This should help us troubleshoot outages in situations where we don't have access to the App Server.
Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.
* See CloudWatch logs in the DTL [CloudWatch console](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logStream:group=logStagingPAAppServer). You should see logs from
* `dmesg`
* `/var/log/messages`
* If you search `districtbuilder` within this stream, application logs …
=> Add CloudWatch logging configuration to App Server

nginx/default.template
Increase `client_body_buffer_size` and `proxy_buffers` so that nginx can handle requests/responses containing polygons with a large number of coordinates in memory. This should stop nginx from buffering requests to disk.
- I allocated 1MB in buffer space because the largest request/response I was able to find in the logs or generate myself was ~700K.
- This change should keep us from buffering to disk in most cases, but since the there's no upper bound on the amount of coordinates included in a Polygon, we may still end up writing to disk if a user draws a big enough shape. The plan is to increase the buffer size now, and monitor the production web server's performance to …
=> Increase nginx buffer sizes

django/publicmapping/publicmapping/settings.py, django/publicmapping/publicmapping/urls.py, django/publicmapping/redistricting/config.py, django/publicmapping/redistricting/health_checks.py, django/publicmapping/requirements.txt, docker-compose.override.yml
This PR adds a `/health-check/` endpoint to app servers so that we can detect when they're out of service. I added the endpoint and a `django-watchman` configuration that checks databases and caches.
- [ x ] PR has a name that won't get you publicly shamed for vagueness
Once this is merged, we'll still have to turn enable Production app monitoring using Panopta.
* Run `docker-compose up --no-deps -d  nginx django`
* Do `curl http://localhost:8080/health-check/ `
* Ensure that the service returns a 500 status code
* Run `docker-compose up -d` to start all services
* Do `curl http://localhost:8080/health-check/ `
* Ensure that the endpoint returns a 200 status code.
Closes …
=> Add Django watchman health check to App Server

django/publicmapping/static/css/core.css
A small issue was introduced when we made a change to turn the "Assign to District" text to black (was illegible -- white text on a white background) that made the text in the bottom left disappear (turned it black on a black background). This reverts that change and uses a different selector to change only the "Assign to District" text color.
**Before**
**After**
* Check out branch, log in, and go to the map page.
* Verify that "Assign to District" is black and text in bottom left is white
=> Fix "Assign to District" text color

django/publicmapping/redistricting/templates/editplan.html
Add default option to competition form dropdowns for county and division.
* Submit a map and check if the form has these default options on the county and division dropdowns. Check to see that you can't submit without selecting a real option for both dropdowns.
Closes [#161266152](https://www.pivotaltracker.com/story/show/161266152)
=> Add default option to competition form dropdowns

django/publicmapping/static/css/core.css
Change base layer picker pill styling.
* Verify that pill looks like what's above, where `Topo` is selected and `Road` is being hovered over
Closes [#161266050](https://www.pivotaltracker.com/story/show/161266050)
=>  Change base layer picker pill styling

django/publicmapping/config/config.xml, django/publicmapping/redistricting/management/commands/fix_stats_typos.py
There are two fields that are showing up as 'n/a' within the application: Incarcerated and Pacific Islander VAP. This fixes the typos in the config file, and also adds a one-off management command that may be used to reload these stats in-place.
* Remember to `vagrant rsync-auto`!
* `vagrant ssh`
* `docker-compose exec django ./manage.py fix_stats_typos prison,vappild CFPOP,N18NHI_PI`
* Wait 10 minutes or so
* Start up the server, log in to view a plan, and ensure that stats for Incarcerated and Pacific Islander VAP do not have any n/a's. Note: the latter of those two stats all show up as 0.0%, because their counts are so low.
Closes  #161485756
=> Fix typos in stats

geoserver/Dockerfile, scripts/update
This PR replaces our GeoServer installation with an Azavea base image. This should simplify our build process and allow us to focus on configuring the GeoServer, rather than configuration _and_ installation.
I removed the relative path for `change_admin_password.sh`  in `scripts/update` because `${CATALINA_HOME}/bin` is on the GeoServer image `PATH`.
* Rebuild the GeoServer using the base image
* Reconfigure the GeoServer using Django management commands
* Interact with the app at [http://localhost:8080](http://localhost:8080) and ensure that the styling for map tiles is correct.
* Make sure you can sign into the GeoServer UI at http://localhost:8080/geoserver, and ensure …
=> Use centralized GeoServer image

docker-compose.production.yml
Bump the number of Gunicorn workers in production. Additionally, use the default worker type instead of `gevent`. 
Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.
* Once the build passes & deploys to staging, see https://staging.pa.districtbuilder.azavea.com
Closes #124
=> Increase number of Gunicorn workers in Production

django/publicmapping/redistricting/management/commands/submission_report.py, django/publicmapping/redistricting/templates/submission_summary.html
Adds a link to the submission report that directs the user to a plan's View page.
- I made the map name into a link; we could also make it into a separate line and say something like "View submitted map on map.drawthelinespa.org". @tgilcrest let me know what you think. 
* Assuming you have a submission already, run `./scripts/server` inside the VM and then in a separate shell `docker-compose exec django bash`.
* Run `./manage.py submission_report 1` (or some other submission ID)
* Once it finishes, `vagrant rsync-back` and then view the HTML file in a browser. Confirm that the map name is now a link.
* If you click the link, it won't work, because there's not really a good way for Django to know what protocol and port are in use when running outside the request / response cycle, so I set …
=> Add link to plan view in submission report

django/publicmapping/config/config.xml, django/publicmapping/requirements.txt, django/publicmapping/static/css/core.css, scripts/configure_pa_data
This PR modifies the config file to add an additional legislative body for 17 districts while still keeping around the 18 district legislative body. Many of the score functions, and even score panels have been reused, but anything relating to target population (even indirectly), needed additional components.
A few additional commits were made to help testing:
* The legislative body dropdown that appears when there are multiple legislative bodies had styling issues which made it unusable. I shifted the other panel down a bit, which fixes it. My hunch is that this styling is probably what we want, but still worth confirming with C70.
* I created a (temporary) 17-district template, uploaded to S3, and modified the config to point to it. Once we have the real template from C70, this can be …
=> Add configuration for 17-district congressional competition

django/publicmapping/redistricting/views.py
Order legislative bodies by number of districts.
This is to ensure that the legislative body with 17 districts shows up first (default) in dropdown.
Legislative bodies were being sorted by region (both were in the same region) and then by order key (both had the same order key of 1 for my local instance). It seems that sort order was then based on some other arbitrary factor which in at least one case resulted in the 18 district map showing up first.
* Restart server and go to select a map page
* Verify that the new legislative body with 17 districts shows up first in the dropdown
Closes #163120488
=> Order legislative bodies by number of districts #163120488

django/publicmapping/redistricting/templates/editplan.html
Add `Incumbent Protection` as a value choice in submit plan form.
* Submit a plan and check if this is one of the options. Select it and check if the db correctly stored it.
Closes [#162929971](https://www.pivotaltracker.com/story/show/162929971)
=> Add `Incumbent Protection` as a value choice in submit plan form

django/publicmapping/publicmapping/templates/account.html, django/publicmapping/static/js/mapping.js
Shorten district labels from "District xx" to just the number "xx". 
Swap colors of districts 5 and 18.
Increase label font size to 13pt.
(Also, add help text on signup form.)
* Serve and view a plan. Check that labels are shortened. 
* District 5 should be a bright red color.
* Font size should have increased from earlier.
* On signup form, help text should show above Organization/School.
Closes [#162930055](https://www.pivotaltracker.com/story/show/162930055), [#163595004](https://www.pivotaltracker.com/story/show/163595004)
=> Update districts labels and colors

django/publicmapping/config/config.xml, django/publicmapping/locale/en/LC_MESSAGES/django.po, django/publicmapping/locale/en/LC_MESSAGES/xmlconfig.po, django/publicmapping/redistricting/calculators.py
Change competitiveness metric for 17 district legislative body to conform to C70's new definition (`|D% - R%| <= 10`).
This updates competitiveness in both the side panel and the leaderboard.
* Check out `develop` and run `./scripts/configure_pa_data` to start from a clean slate
* Run `./scripts/update` and then `./scripts/server`
* View the '17 Districts Congressional' map and note the number of competitive districts (it currently has 5 competitive districts, but the default template will soon change as per https://github.com/azavea/district-builder-dtl-pa/pull/148#event-2128298929)
* Check out this branch
* Run `docker-compose exec django bash` and then `./manage.py removescoreconfig` and `./manage.py setup config/config.xml -f` within the container (this will need to be run manually in …
=> Change competitiveness metric

scripts/configure_pa_data
Update 17-district template on configuration by pulling a new zipped shapefile from S3 with the new template. This supplements actually updating this template on the production database. 
* Reconfigure data with `./scripts/configure_pa_data`
* Start the server `./scripts/server`
* Create an account and make a plan with the `17 Districts Congressional` template -- check to see that it looks like the new template and isn't valid already
Closes [#163527303](https://www.pivotaltracker.com/story/show/163527303)
=> Update 17 district template

django/publicmapping/publicmapping/urls.py, django/publicmapping/redistricting/admin.py
Exposes certain user profile fields like county and school/organization to both the user list and detail views.
- Also fixes a minor issue where admin panel URL prefixes did not include a `/` after the `admin` portion of the URL, leading to URLs like `/adminauth/` and `/adminredistricting/`.
- Load the User Admin list at http://localhost:8080/admin/auth/user/
- The users should be listed with columns for profile org/school, county, division and social media handles
- Select a user and open the detail view
- At the bottom should be a section with fields for the same values shown in the list view, plus two fields for the user's "How did you hear about us?" and "Where?" response
Closes [PT162929871](https://www.pivotaltracker.com/story/show/162929871)
=> Add Profile fields to User list and detail view in Admin panel

django/publicmapping/redistricting/admin.py
To help the World Bank export data using the user list view, this adds the "How did you hear about us?" and "Where did you hear about us?" (Shortened to "How did you hear?" and "Where did you hear?" respectively) to the user list view.
- Open the Admin panel and navigate to the User list view
- You should see a column for "How did you hear?" and "Where did you hear?"
Closes [PT164139210](https://www.pivotaltracker.com/story/show/164139210)
=> Add How and Where did you hear about us to the admin user list

django/publicmapping/redistricting/management/commands/submission_report.py, django/publicmapping/redistricting/templates/submission_summary.html
Minor changes to the submission report generation script to support the 17 district contest:
* Point to the 17 district score panel
* Hardcode the host, so we don't need to run sed command
* Update map url to use ArcGIS basemap
- ~~[ ] PR has a name that won't get you publicly shamed for vagueness~~
I'm currently running this to export the contest submissions, and will merge when it's complete.
=> Update submission report for 17 district instance
